source 'https://rubygems.org'

gem "compass", "~> 1.0.0.alpha.18"
gem "sass", "~> 3.3.0.rc.4"
gem "susy", "~> 2.0.0.rc.1"
gem "breakpoint", "~> 2.4.1"

require 'rbconfig'
gem 'wdm', '>= 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw/i